import Head from 'next/head'
import Footer from '../components/global/Footer'
import NavBar from '../components/global/nav'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Real Estate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      <div>Body</div>
      <Footer/>
    </div>
  )
}
